Иправлено условие задания mobile-graphic/product-cards
netology-code/mq-homeworks pull request #21
Opened 2018-05-26 22:14 UTC by AndrXxX

Доработано условие задания mobile-graphic/product-cards по согласованию со Станиславом.

2018-05-28 06:33 UTC, dfitiskin commented
Каким Станиславом? Что было с ним согласовано? Как изменилось условие? )

2018-05-28 06:55 UTC, dfitiskin requested changes
Обратил внимание на ряд моментов, которые как мне кажется нужно исправить.

2018-05-28 06:55 UTC, dfitiskin commented on mobile-graphic/product-cards/index.html
> +            <p>Счетчик банкнот Cassida 5550 UV- компактный и надежный счетчик для сферы ритейла. Единственный счетчик в России класса «Эконом» полностью на русском языке и с технологией ValuCount. Бо
Нет пробела после `UV`. Используется ли тут длинное тире `—`?

2018-05-28 06:55 UTC, dfitiskin commented on mobile-graphic/product-cards/index.html
> +        <img class="product__img" src="img/product2.jpg" alt="Превью товара">
Имя файла так себе. Должно быть `does-1200.jpg`

2018-05-28 06:55 UTC, dfitiskin commented on mobile-graphic/product-cards/README.md
> +4. Сделайте так, чтобы блок с ценой и кнопка «Купить» были прижаты к нижней границе элемента с классом `product__footer`.
Насколько оборот `прижаты` понятен обывателю?

2018-05-30 21:37 UTC, AndrXxX commented
Здравствуйте! Исправил указанные замечания. Внесение изменений потребовалось для того, чтобы студенты могли видеть разницу при выполнении каждого пункта задания (ранее выполнение некоторых пунктов задания не влияло на внешний вид страницы и в связи с этим многие задавались вопросом - зачем выполнять эти условия если не видно разницы). Изменения были согласованы с руководителем курса MQ Станиславом Мельниковым ( https://vk.com/melnik909 ).

2018-05-31 04:55 UTC, dfitiskin requested changes
Все причины изменений, и к какому результату они приводят (не в коде, а верхнеуровнево), необходимо писать в описании коммитов, и делать дайджест в описании пул-реквеста. Иначе мы имеем коммиты с одинаковыми названиями, потому что когда через пол года внесем еще правки, мы просто «исправлено» заменим на «улучшено». Ни то ни другое не несет полезной информации, потому что коммит уже подразумевает изменения.

С формулировкой «прижаты» / «позиционироваться» не нужно просто возвращать назад. Я думаю что можно сформулировать более понятно без жаргона. Если нет представления как это сделать, можно это обсудить.

2018-05-31 04:55 UTC, dfitiskin commented on mobile-graphic/product-cards/README.md
> +1. Для устройств с шириной экрана от `769px` расположите карточки товара в ряд, используя flexbox. Ширина каждой карточки должна быть `32%`. Карточки не должны растягиваться по высоте и должны позици
По твоему «позиционироваться» звучит понятнее чем «прижаты»?

2018-06-23 19:31 UTC, AndrXxX commented
Писал вам в личные сообщения в слаке, но ответ так и не получил. Дайджест добавлю, хотел  еще обсудить формулировоку про прижатие к границе родителя.
Варианты:
должны быть прижаты к верхней границе родителя
должны позиционироваться по верхней границе родителя
должны быть выровнены по верхней границе родителя
должны располагаться вплотную к верхней границе родителя
должны прилипать к верхней границе родителя
Подскажите какой из них подойдет лучше? Или возможно у вас есть другие идеи?

2018-11-27 23:35 UTC, AndrXxX commented
Здравствуйте! Примите, пожалуйста, Pull-request. Студенты на каждом потоке спотыкаются при выполнении этих домашних работ.

2018-11-28 06:51 UTC, merged